HELPDESK = {
    "main": {"message": "Hello 👋 I am SURAKSHA Security Assistant. How can I help you today?", "options": ["What is SURAKSHA?", "Purpose of SURAKSHA", "Developer Information", "Risk Metrics", "Network Scan", "Web Scan", "SSL/TLS Checker"]},
    "What is SURAKSHA?": {"message": "SURAKSHA is an intelligent cybersecurity platform that performs vulnerability assessment, network scanning, traffic monitoring, IDS/IPS protection.", "options": ["Back"]},
    "Purpose of SURAKSHA": {"message": "The purpose of SURAKSHA is to proactively identify security weaknesses before attackers exploit them.", "options": ["Back"]},
    "Developer Information": {"message": "SURAKSHA was developed by K Pranav Eswar as an MCA Major Project.", "options": ["Back"]},
    "Risk Metrics": {"message": "Select a risk level.", "options": ["Low Risk", "Medium Risk", "Critical Risk", "Back"]},
    "Low Risk": {"message": "Low Risk vulnerabilities have minimal impact and usually do not allow direct exploitation.", "options": ["Back"]},
    "Medium Risk": {"message": "Medium Risk vulnerabilities can expose information or weaken security controls.", "options": ["Back"]},
    "Critical Risk": {"message": "Critical vulnerabilities can lead to complete compromise, unauthorized access, or remote code execution.", "options": ["Back"]},
    "Network Scan": {"message": "Select a Network Scan topic.", "options": ["Port Scan", "Banner Grabbing", "Service Detection", "Version Detection", "OS Detection", "Vulnerability Scripts", "Full Scan", "Back"]},
    "Port Scan": {"message": "Port scanning identifies open TCP and UDP ports on a target system.", "options": ["Back"]},
    "Banner Grabbing": {"message": "Banner grabbing retrieves software names, versions, and service information.", "options": ["Back"]},
    "Service Detection": {"message": "Service detection identifies applications running on discovered ports.", "options": ["Back"]},
    "Version Detection": {"message": "Version detection identifies exact software versions for vulnerability analysis.", "options": ["Back"]},
    "OS Detection": {"message": "OS detection identifies the operating system running on a target host.", "options": ["Back"]},
    "Vulnerability Scripts": {"message": "Nmap NSE scripts are used to identify known vulnerabilities and security weaknesses.", "options": ["Back"]},
    "Full Scan": {"message": "Full Scan performs host discovery, port scanning, service detection, OS detection and vulnerability analysis.", "options": ["Back"]},
    "Web Scan": {"message": "Select a Web Scan topic.", "options": ["Security Headers", "Sensitive Paths", "SQL Injection", "XSS Scan", "HTTPS Check", "Full Web Scan", "Back"]},
    "Security Headers": {"message": "Checks CSP, HSTS, X-Frame-Options and other security headers.", "options": ["Back"]},
    "Sensitive Paths": {"message": "Searches for exposed admin panels, backups, and hidden directories.", "options": ["Back"]},
    "SQL Injection": {"message": "Tests whether user input can manipulate database queries.", "options": ["Back"]},
    "XSS Scan": {"message": "Detects Cross Site Scripting vulnerabilities in web applications.", "options": ["Back"]},
    "HTTPS Check": {"message": "Validates SSL certificates and TLS configuration.", "options": ["Back"]},
    "Full Web Scan": {"message": "Combines headers, paths, SQLi, XSS and HTTPS testing.", "options": ["Back"]},
    "SSL/TLS Checker": {"message": "Checks certificate validity, protocols, ciphers and cryptographic strength.", "options": ["Back"]}
}